#!/bin/bash

# Silly icns format...

rm -r papercraft.iconset
mkdir papercraft.iconset
cd papercraft.iconset

for s in 16 32 64 128 256 512
do
    SZ=${s}x${s}
    gm convert -background None ../../../papercraft.svg -resize $SZ -gravity center -extent $SZ icon_$SZ.png
done

cp icon_32x32.png icon_16x16@2x.png
mv icon_64x64.png icon_32x32@2x.png
cp icon_256x256.png icon_128x128@2x.png
cp icon_512x512.png icon_256x256@2x.png

# Now run "iconutil -c icns papercraft.iconset" to build the icon
#
# For the backgorund
# gm convert -units PixelsPerInch installer_background_.png -density 72 installer_background.png
