#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"

#export LD_LIBRARY_PATH="$HERE/usr/lib/gdk-pixbuf/loaders/"
export GDK_PIXBUF_MODULE_FILE="$HERE/usr/lib/gdk-pixbuf/loaders.cache"

exec "$HERE/usr/bin/papercraft" "$@"
