#!/bin/bash
set -e

mkdir papercraft
cd papercraft
tar -xf ../source.tar
source $HOME/.cargo/env
BINDGEN_EXTRA_CLANG_ARGS=-I/usr/lib/gcc/x86_64-linux-gnu/7/include cargo build --release
cd ..

export VERSION="$1"
export ARCH=x86_64
rm -rf AppDir
./linuxdeploy --appdir=AppDir
mkdir -p AppDir/usr/share/metainfo/
cp papercraft/distro/papercraft.desktop AppDir/usr/share/applications/
cp papercraft/distro/com.rodrigorc.papercraft.appdata.xml AppDir/usr/share/metainfo/
cp papercraft/target/release/papercraft AppDir/usr/bin/
cp papercraft/src/papercraft.png AppDir/usr/share/icons/hicolor/128x128/apps/
./linuxdeploy \
    --appdir=AppDir \
    --desktop-file=AppDir/usr/share/applications/papercraft.desktop \
    --output appimage \
    --exclude-library="libglib-2.0.*" \
    --custom-apprun=apprun
