name: BuildMacOS

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true

jobs:
  papercraft:
    name: ${{ inputs.name }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Rustup
        run: |
          rustup target add x86_64-apple-darwin
      - name: Create DMG
        run: |
          brew install create-dmg
      - name: Build x86
        run: |
          cargo build --release --target=x86_64-apple-darwin
      - name: Build Arm86
        run: |
          cargo build --release --target=aarch64-apple-darwin
      - name: Build DMG
        run: |
          mkdir -p app_folder/Papercraft.app/Contents/MacOS
          mkdir -p app_folder/Papercraft.app/Contents/Resources
          cd distro/macos
          iconutil -c icns papercraft.iconset
          cd ../..
          cp distro/macos/papercraft.icns app_folder/Papercraft.app/Contents/Resources/Papercraft.icns
          cp distro/macos/PkgInfo app_folder/Papercraft.app/Contents/
          cp distro/macos/Info.plist app_folder/Papercraft.app/Contents/
          lipo -create target/aarch64-apple-darwin/release/papercraft target/x86_64-apple-darwin/release/papercraft -output \
            app_folder/Papercraft.app/Contents/MacOS/Papercraft
          create-dmg \
            --volname "Papercraft" \
            --volicon "distro/macos/papercraft.icns" \
            --background "distro/macos/installer_background.png" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "Papercraft.app" 200 200 \
            --app-drop-link 600 200 \
            --hide-extension "Papercraft.app" \
            "Papercraft-${{ inputs.name }}-MacOS.dmg" \
            "app_folder/"

      - name: Upload artifact MacOS
        uses: actions/upload-artifact@v4
        with:
          name: Papercraft-${{ inputs.name }}-MacOS.dmg
          path: Papercraft-${{ inputs.name }}-MacOS.dmg
          if-no-files-found: error

