name: ManualRelease

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        required: true

jobs:
  build_release:
    permissions:
      contents: write
    name: BuildRelease
    uses: ./.github/workflows/build_release.yml
    with:
      tag_name: ${{ inputs.tag_name }}
