name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    permissions:
      contents: write
    name: BuildRelease
    uses: ./.github/workflows/build_release.yml
    with:
      tag_name: ${{ github.ref_name }}

