#!/bin/bash
set -e
VERSION="$(git describe --tag)"
source ./win64env
cargo build --release --target x86_64-pc-windows-gnu
rm -rf pkg
mkdir -p pkg
cd pkg
ln -s ../win64inst papercraft
rm -f "../Papercraft-$VERSION-win64.zip"
zip -r "../Papercraft-$VERSION-win64.zip" papercraft
cd ..
rm -r pkg
